name: "Catalyst Stats Processor"
description: "Trigger Netlify background function"
inputs:
  project_ids:
    description: "Comma-separated project IDs"
    required: true
runs:
  using: "node20"
  main: "dist/index.js"
