# action.yml
name: "Discord Stats"
description: "Trigger Discord stats collection via Netlify background function"

inputs:
  guild-id:
    description: "Server (guild) ID"
    required: true
  backfill:
    description: "Whether to backfill from Jan of BACKFILL_YEAR"
    required: false
    default: "false"
  backfill-year:
    description: "Year to backfill from (ignored if backfill=false)"
    required: false
    default: ""
  discord-token:
    description: "Optional Discord analytics token to pass to the background function"
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "18"

    - name: Install dependencies
      working-directory: ${{ github.action_path }}
      shell: bash
      run: npm install

    - name: Run stats script
      shell: bash
      run: node ${{ github.action_path }}/getStats.js
      env:
        GUILD_ID: ${{ inputs.guild-id }}
        BACKFILL: ${{ inputs.backfill }}
        BACKFILL_YEAR: ${{ inputs.backfill-year }}
        DISCORD_TOKEN: ${{ inputs.discord-token }}
