# action.yml
name: "GitHub Stats"
description: "Trigger GitHub stats collection via Netlify background function"

inputs:
  org:
    description: "GitHub organization name"
    required: true
  repo:
    description: "GitHub repository name"
    required: true
  github-token:
    description: "GitHub token for API access"
    required: true

runs:
  using: composite
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "18"

    - name: Install dependencies
      working-directory: ${{ github.action_path }}
      shell: bash
      run: npm install

    - name: Run stats script
      shell: bash
      run: node ${{ github.action_path }}/getStats.js
      env:
        ORG: ${{ inputs.org }}
        REPO: ${{ inputs.repo }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
