name: DRep Delegation Action

on:
  schedule:
    - cron: '20 0 * * 1'  # Runs at 00:20 UTC every Monday
    - cron: '20 0 * * 4'  # Runs at 00:20 UTC every Thursday
  workflow_dispatch:

jobs:
  fetch-delegation-info:
    if: github.repository == 'MeshJS/governance'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: npm install
      
    - name: Run delegation info script
      env:
        KOIOS_API_KEY: ${{ secrets.KOIOS_API_KEY }}
        SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      run: node scripts/drep-voting/drep-delegation-info.js 