name: Release Catalyst Stats Action

on:
  push:
    tags:
      - 'catalyst-stats-action@*'
    paths:
      - 'apps/shared-backend/github-actions/catalyst-stats-action/**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'apps/shared-backend/github-actions/catalyst-stats-action/package-lock.json'

      - name: Install dependencies
        run: |
          cd apps/shared-backend/github-actions/catalyst-stats-action
          npm ci

      - name: Build action
        run: |
          cd apps/shared-backend/github-actions/catalyst-stats-action
          npm run build

      - name: Release with Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: |
            Changes in this Release:
            ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
          files: |
            ./apps/shared-backend/github-actions/catalyst-stats-action/dist/index.js
            ./apps/shared-backend/github-actions/catalyst-stats-action/action.yml
            ./apps/shared-backend/github-actions/catalyst-stats-action/package.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 