name: Update Cardano Dashboard DRep Metadata

on:
  schedule:
    - cron: '30 1 * * *'  # Run at 1:30 AM UTC every day
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-drep-metadata:
    if: github.repository == 'MeshJS/governance'
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          cd apps/cardano-dashboard
          npm install
          
      - name: Update DRep Metadata
        continue-on-error: true
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          KOIOS_API_KEY: ${{ secrets.KOIOS_API_KEY }}
        run: |
          cd apps/cardano-dashboard
          npx ts-node scripts/update-drep-metadata.ts 